# Generated by Django 6.0.6 on 2026-06-09 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_audio_guia',
            field=models.BooleanField(default=False, verbose_name='Audioguia'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_banheiro_adaptado',
            field=models.BooleanField(default=False, verbose_name='Banheiro adaptado (PCD)'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_braile',
            field=models.BooleanField(default=False, verbose_name='Informações em Braille'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_elevador',
            field=models.BooleanField(default=False, verbose_name='Elevador'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_estacionamento',
            field=models.BooleanField(default=False, verbose_name='Vaga de estacionamento PCD'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_libras',
            field=models.BooleanField(default=False, verbose_name='Atendimento em Libras'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_piso_tatil',
            field=models.BooleanField(default=False, verbose_name='Piso tátil'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='ac_rampa',
            field=models.BooleanField(default=False, verbose_name='Rampa de acesso'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='nivel_acessibilidade',
            field=models.CharField(choices=[('nao_avaliado', 'Não avaliado'), ('basico', 'Básico'), ('intermediario', 'Intermediário'), ('completo', 'Completo')], default='nao_avaliado', max_length=20, verbose_name='Nível de Acessibilidade'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='obs_acessibilidade',
            field=models.TextField(blank=True, verbose_name='Observações de acessibilidade'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_audio_guia',
            field=models.BooleanField(default=False, verbose_name='Audioguia'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_banheiro_adaptado',
            field=models.BooleanField(default=False, verbose_name='Banheiro adaptado (PCD)'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_braile',
            field=models.BooleanField(default=False, verbose_name='Informações em Braille'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_elevador',
            field=models.BooleanField(default=False, verbose_name='Elevador'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_estacionamento',
            field=models.BooleanField(default=False, verbose_name='Vaga de estacionamento PCD'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_libras',
            field=models.BooleanField(default=False, verbose_name='Atendimento em Libras'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_piso_tatil',
            field=models.BooleanField(default=False, verbose_name='Piso tátil'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='ac_rampa',
            field=models.BooleanField(default=False, verbose_name='Rampa de acesso'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='nivel_acessibilidade',
            field=models.CharField(choices=[('nao_avaliado', 'Não avaliado'), ('basico', 'Básico'), ('intermediario', 'Intermediário'), ('completo', 'Completo')], default='nao_avaliado', max_length=20, verbose_name='Nível de Acessibilidade'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='obs_acessibilidade',
            field=models.TextField(blank=True, verbose_name='Observações de acessibilidade'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='tour_foto_360',
            field=models.ImageField(blank=True, help_text='Exporte do app "360 Photo Camera" no Android e faça upload aqui.', null=True, upload_to='tours360/', verbose_name='Foto 360° (equirretangular)'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='tour_streetview_url',
            field=models.URLField(blank=True, help_text='Ex: https://www.google.com/maps/embed?pb=...', verbose_name='URL do Google Street View'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='tour_tipo',
            field=models.CharField(choices=[('nenhum', 'Sem tour'), ('pannellum', 'Foto 360° (upload)'), ('streetview', 'Google Street View')], default='nenhum', max_length=20, verbose_name='Tipo de Tour 360°'),
        ),
        migrations.CreateModel(
            name='FotoTour360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Nome da cena')),
                ('foto', models.ImageField(upload_to='tours360/', verbose_name='Foto equirretangular')),
                ('ordem', models.IntegerField(default=0)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_360', to='portal.pontoturistico')),
            ],
            options={
                'verbose_name': 'Foto do Tour 360°',
                'verbose_name_plural': 'Fotos do Tour 360°',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_local', models.CharField(choices=[('ponto', 'Ponto Turístico'), ('estab', 'Estabelecimento')], max_length=10)),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de acessibilidade')),
                ('comentario', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_acessibilidade', to='portal.estabelecimento')),
                ('ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_acessibilidade', to='portal.pontoturistico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Acessibilidade',
                'verbose_name_plural': 'Avaliações de Acessibilidade',
                'unique_together': {('usuario', 'estabelecimento'), ('usuario', 'ponto')},
            },
        ),
    ]
