# Generated by Django 6.0.6 on 2026-06-10 18:40

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_estabelecimento_ac_audio_guia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estabelecimentos/', validators=[portal.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', validators=[portal.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='fototour360',
            name='foto',
            field=models.ImageField(upload_to='tours360/', validators=[portal.models.validate_image_extension], verbose_name='Foto equirretangular'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pontos/', validators=[portal.models.validate_image_extension]),
        ),
    ]
