# Generated by Django 6.0.6 on 2026-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_seed_eventos_estabelecimentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data_evento'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Texto detalhado exibido na página do evento.', verbose_name='Descrição completa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, help_text='Endereço ou local do evento, ex.: "Praia de Itaúna, Saquarema". Usado para o mapa.', max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição curta'),
        ),
    ]
