# Generated by Django 6.0.6 on 2026-06-19 13:46

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_eventos_locais'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimentos', to=settings.AUTH_USER_MODEL, verbose_name='Parceiro responsável'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=10, verbose_name='Status de publicação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Admin'), ('comum', 'Comum'), ('parceiro', 'Parceiro')], default='comum', max_length=10),
        ),
        migrations.CreateModel(
            name='EdicaoEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteracoes', models.JSONField(default=dict, help_text='Campos alterados no formato {campo: {de, para}}.')),
                ('imagem_proposta', models.ImageField(blank=True, null=True, upload_to='edicoes/', validators=[portal.models.validate_image_extension])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('observacao_admin', models.TextField(blank=True, verbose_name='Observação do administrador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes', to='portal.estabelecimento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edição de Estabelecimento',
                'verbose_name_plural': 'Edições de Estabelecimentos (parceiros)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
