# Generated by Django 6.0.6 on 2026-06-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_estabelecimento_proprietario_estabelecimento_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoParceria',
            fields=[
            ],
            options={
                'verbose_name': 'Solicitação de Parceria',
                'verbose_name_plural': '⭐ Solicitações de Parceria',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.estabelecimento',),
        ),
    ]
